config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  get "feed", to: "feed#index", as: "feed"
  get "feed/events", to: "feed#events", as: "event_feed"
  get "feed/modules", to: "feed#modules", as: "module_feed"

  get "user_events", to: "cpd_events#user_events", as: "user_events"
  get "user_modules", to: "unit_modules#user_modules", as: "user_modules"
  resources :cpd_events do
      resources :announcements
  end
  resources :unit_modules do
      resources :enrollments
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "splash#index"

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
    def index
	@events = CpdEvent.limit(3)
	@modules =  UnitModule.limit(3)
    end
    def events
	@events = CpdEvent.limit(3)
    end

    def modules
	@modules =  UnitModule.limit(3)
    end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/views/feed/events.html.erb
<div class="nav nav-tabs">
    <li class = "nav-item">
	<%= link_to "Events", event_feed_path, class: "nav-link active" %>
    </li>
    <li class = "nav-item">
	<%= link_to "Modules", module_feed_path, class: "nav-link" %>
    </li>
</div>
<% @events.each do |event| %>
    <p>
	<strong>
	    <%= event.name %>
	</strong>
    </p>

    <p>
	<%= event.date %>
    </p>

<% end %>

app/views/feed/index.html.erb
<h2 class = "text-center">Events</h3>
<div class = "row">
<% @events.each do |event|%>
    <%= render "cpd_events/cpd_event", cpd_event: event %>
<% end %>
</div>
<hr>
<h2 class = "text-center">Modules</h2>
<div class = "row">
<% @modules.each do |m|%>
    <%= render "unit_modules/unit_module", unit_module: m%>
<% end %>
</div>

app/views/feed/modules.html.erb
<div class="nav nav-tabs">
    <li class = "nav-item">
	<%= link_to "Events", event_feed_path, class: "nav-link " %>
    </li>
    <li class = "nav-item">
	<%= link_to "Modules", module_feed_path, class: "nav-link active" %>
    </li>
</div>

<% @modules.each do |m| %>
<% end %>