config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  get "feed", to: "feed#index", as: "feed"
  get "feed/events", to: "feed#events", as: "event_feed"
  get "feed/modules", to: "feed#modules", as: "module_feed"

  get "user_events", to: "cpd_events#user_events", as: "user_events"
  get "user_modules", to: "unit_modules#user_modules", as: "user_modules"
  resources :cpd_events do
      resources :announcements
  end
  resources :unit_modules do
      resources :enrollments
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "splash#index"

end

app/models/announcement.rb
class Announcement < ApplicationRecord
    belongs_to :cpd_event
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    @cpd_event = CpdEvent.find(params[:cpd_event_id])
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
	  format.html { redirect_to @announcement.cpd_event, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
	  format.html { redirect_to @announcement.cpd_event, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to cpb_events_path, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:cpd_event_id, :user_id, :title, :body)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for([@cpd_event, @announcement], local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :cpd_event_id, value: @cpd_event.id %>

    <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Cpdevent</th>
      <th>Announcement</th>
      <th>User</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.cpdevent_id %></td>
        <td><%= announcement.announcement_id %></td>
        <td><%= announcement.user_id %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.body %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpdevent:</strong>
  <%= @announcement.cpdevent_id %>
</p>

<p>
  <strong>Announcement:</strong>
  <%= @announcement.announcement_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @announcement.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @announcement.body %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>