config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  get "feed", to: "feed#index", as: "feed"
  get "feed/events", to: "feed#events", as: "event_feed"
  get "feed/modules", to: "feed#modules", as: "module_feed"

  get "user_events", to: "cpd_events#user_events", as: "user_events"
  get "user_modules", to: "unit_modules#user_modules", as: "user_modules"
  resources :cpd_events do
      resources :announcements
  end
  resources :unit_modules do
      resources :enrollments
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "splash#index"

end

app/models/cpd_event.rb
class CpdEvent < ApplicationRecord
    has_many :announcements
    has_and_belongs_to_many :users
    mount_uploader :image, ImageUploader
end

app/controllers/cpd_events_controller.rb
class CpdEventsController < ApplicationController
  before_action :set_cpd_event, only: [:show, :edit, :update, :destroy]

  def user_events
    @cpd_events = current_user.cpd_events
  end
  # GET /cpd_events
  # GET /cpd_events.json
  def index
    @cpd_events = CpdEvent.all
  end


  # GET /cpd_events/1
  # GET /cpd_events/1.json
  def show
      @announcements = @cpd_event.announcements
  end

  # GET /cpd_events/new
  def new
    @cpd_event = CpdEvent.new
  end

  # GET /cpd_events/1/edit
  def edit
  end

  # POST /cpd_events
  # POST /cpd_events.json
  def create
    @cpd_event = CpdEvent.new(cpd_event_params)

    respond_to do |format|
      if @cpd_event.save
        format.html { redirect_to @cpd_event, notice: 'Cpd event was successfully created.' }
        format.json { render :show, status: :created, location: @cpd_event }
      else
        format.html { render :new }
        format.json { render json: @cpd_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpd_events/1
  # PATCH/PUT /cpd_events/1.json
  def update
    respond_to do |format|
      if @cpd_event.update(cpd_event_params)
        format.html { redirect_to @cpd_event, notice: 'Cpd event was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpd_event }
      else
        format.html { render :edit }
        format.json { render json: @cpd_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpd_events/1
  # DELETE /cpd_events/1.json
  def destroy
    @cpd_event.destroy
    respond_to do |format|
      format.html { redirect_to cpd_events_url, notice: 'Cpd event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cpd_event
      @cpd_event = CpdEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cpd_event_params
      params.require(:cpd_event).permit(:cpd_event_id, :name, :date, :description, :image)
    end
end

app/helpers/cpd_events_helper.rb
module CpdEventsHelper
end

app/views/cpd_events/_cpd_event.html.erb
<div class = "col-md-4 d-flex align-items-stretch">
<div class = "card my-3">
    <%= image_tag cpd_event.get_image, alt: "Card image cap", class: "  card-img-top img-fluid mw-100 mh-100" %>
    <div class="card-body">
	<h3 class="card-title"><%= link_to cpd_event.name, cpd_event%></h3>
	<p class = "card-text text-secondary">
	    <%= fa_icon "calendar", class: "text-secondary"%> <%= friendly_date(cpd_event.date) %><br>
	    <%= fa_icon "hourglass-start", class: "text-secondary"%> <%= friendly_time(cpd_event.date) %>
	</p>

    </div>
</div>
</div>

app/views/cpd_events/_form.html.erb
<h1> hi</h1>
<%= form_with(model: cpd_event, local: true) do |form| %>
  <% if cpd_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cpd_event.errors.count, "error") %> prohibited this cpd_event from being saved:</h2>

      <ul>
      <% cpd_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.datetime_select :date , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description , class: "form-control"%>
  </div>

  <div class = "form-group">
      <%= form.label :image%>
      <%= form.file_field :image, class: "form-control-file"%>
  </div>


  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cpd_events/edit.html.erb
<h1>Editing Cpd Event</h1>

<%= render 'form', cpd_event: @cpd_event %>

<%= link_to 'Show', @cpd_event %> |
<%= link_to 'Back', cpd_events_path %>

app/views/cpd_events/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "card-deck">
<%= render @cpd_events %>
</div>

app/views/cpd_events/new.html.erb
<h1>New Cpd Event</h1>

<%= render 'form', cpd_event: @cpd_event %>

<%= link_to 'Back', cpd_events_path %>

app/views/cpd_events/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "row">
    <div class = "col-md-4 mr-4">
	<%= image_tag @cpd_event.get_image, alt: "Card image cap", class: "img-thumbnail mx-auto  d-block", style: "max-width: 50vw; max-height: 50vh;" %>
  %>
    </div>


    <div class = "col-md-6">

    <h1><%= @cpd_event.name %></h1>
    <p class = "text-secondary">
	<%= fa_icon "calendar", class: "text-secondary"%> <%= friendly_date(@cpd_event.date) %><br>
	<%= fa_icon "hourglass-start", class: "text-secondary"%> <%= friendly_time(@cpd_event.date) %>
    </p>

	<p>
	    <%= @cpd_event.description %>
	</p>
    </div>
</div>
<hr>
<h3 class = "text-center">Announcements</h3>
<p class = "text-center"><%= link_to "Make announcement", new_cpd_event_announcement_path(@cpd_event), class: "text-center" %></p>
<% if @announcements.blank? %>
    <h5 class = "text-center">No Announcements</h5>
<% end %>
<% @announcements.each do |announcement| %>
    <h5><%= announcement.title %></h5>
    <p><%= announcement.body %></p>
<% end %>

app/views/cpd_events/user_events.html.erb
<div class = "card-deck">
    <%= render @cpd_events %>
</div>