config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  get "feed", to: "feed#index", as: "feed"
  get "feed/events", to: "feed#events", as: "event_feed"
  get "feed/modules", to: "feed#modules", as: "module_feed"

  get "user_events", to: "cpd_events#user_events", as: "user_events"
  get "user_modules", to: "unit_modules#user_modules", as: "user_modules"
  resources :cpd_events do
      resources :announcements
  end
  resources :unit_modules do
      resources :enrollments
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "splash#index"

end

app/models/announcement.rb
class Announcement < ApplicationRecord
    belongs_to :cpd_event
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
    def get_image 
	if self.image.url.present?
	    self.image.url
	else
	    "default.png"
	end
    end
end

app/models/cpd_event.rb
class CpdEvent < ApplicationRecord
    has_many :announcements
    has_and_belongs_to_many :users
    mount_uploader :image, ImageUploader
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :unit_module
    belongs_to :user
    has_one :status
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user 
end

app/models/status.rb
class Status < ApplicationRecord
    belongs_to :enrollment
end

app/models/unit_module.rb
class UnitModule < ApplicationRecord
    has_many :enrollments
    has_many :users, through: :enrollments
    mount_uploaders :files, FileUploader
    serialize :files, JSON
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable

    validates :prc_number, uniqueness: true

    has_one :profile 
    has_many :enrollments
    has_many :unit_modules, through: :enrollments

    has_and_belongs_to_many :cpd_events

    def email_required?
	false
    end

    def email_changed?
	false
    end

    def is_student m
	self.unit_modules.exists?(m)
    end

end

app/controllers/cpd_events_controller.rb
class CpdEventsController < ApplicationController
  before_action :set_cpd_event, only: [:show, :edit, :update, :destroy]

  def user_events
    @cpd_events = current_user.cpd_events
  end
  # GET /cpd_events
  # GET /cpd_events.json
  def index
    @cpd_events = CpdEvent.all
  end


  # GET /cpd_events/1
  # GET /cpd_events/1.json
  def show
      @announcements = @cpd_event.announcements
  end

  # GET /cpd_events/new
  def new
    @cpd_event = CpdEvent.new
  end

  # GET /cpd_events/1/edit
  def edit
  end

  # POST /cpd_events
  # POST /cpd_events.json
  def create
    @cpd_event = CpdEvent.new(cpd_event_params)

    respond_to do |format|
      if @cpd_event.save
        format.html { redirect_to @cpd_event, notice: 'Cpd event was successfully created.' }
        format.json { render :show, status: :created, location: @cpd_event }
      else
        format.html { render :new }
        format.json { render json: @cpd_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpd_events/1
  # PATCH/PUT /cpd_events/1.json
  def update
    respond_to do |format|
      if @cpd_event.update(cpd_event_params)
        format.html { redirect_to @cpd_event, notice: 'Cpd event was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpd_event }
      else
        format.html { render :edit }
        format.json { render json: @cpd_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpd_events/1
  # DELETE /cpd_events/1.json
  def destroy
    @cpd_event.destroy
    respond_to do |format|
      format.html { redirect_to cpd_events_url, notice: 'Cpd event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cpd_event
      @cpd_event = CpdEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cpd_event_params
      params.require(:cpd_event).permit(:cpd_event_id, :name, :date, :description, :image)
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
    def index
	@events = CpdEvent.limit(3)
	@modules =  UnitModule.limit(3)
    end
    def events
	@events = CpdEvent.limit(3)
    end

    def modules
	@modules =  UnitModule.limit(3)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profile = Profile.find(current_user.id)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :first_name, :last_name, :total_units, :mobile_number, :region, :province, :city)
    end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
      if user_signed_in?
	  redirect_to feed_path 
      end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def friendly_date(d)
	d.strftime("%b %d %Y")
    end

    def friendly_time(d)
	d.strftime("%H:%M:%S")
    end

    def friendly_created_date(d)
	friendly_date d.created_at
    end

    def friendly_created_time(d)
	friendly_time d.created_at
    end
end

app/helpers/cpd_events_helper.rb
module CpdEventsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/unit_modules_helper.rb
module UnitModulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kumar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg bg-white border-bottom">
  <%= link_to root_path, class: "navbar-left" do %>
      <%= image_tag "kumarx.png", id: "nav-logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
	  <%= link_to "Modules", unit_modules_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
	  <%= link_to "Events", cpd_events_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class = "navbar-nav">
	<% if not user_signed_in? or not current_user.profile.present? %>
	<li class = "nav-item">
	    <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
	</li>
	<li class = "nav-item">
	    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
	</li>
	<% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    <%= (current_user.profile.first_name + " " + current_user.profile.last_name) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	    <%= link_to "View Profile", profile_path(current_user), class: "dropdown-item"%>
	    <%= link_to "My Events", user_events_path,class: "dropdown-item" %>
	    <%= link_to "My Modules", user_modules_path,class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
	    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>

	<% end %>
    </ul>
  </div>
</nav>
<div class = "container mt-3" >
    <%= yield %>
</div>
  </body>
</html>